### ISSUE TITLE
sphinx-autodocgen raise exception trying to parse the "ObjectMember"s

### ISSUE THREAD

**Issue by ceccopierangiolieugenio** [ben-spiller/sphinx-autodocgen#3]
I updated sphinx to
```
Sphinx==8.1.3
sphinx-autodocgen==1.3
sphinx-basic-ng==1.0.0b2
sphinx-epytext==0.0.4
sphinx-rtd-theme==3.0.1
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
```

when I try to generate the doc I have this issue:

```bash
 $ sphinx-build -v -T "source" "build"
Running Sphinx v8.1.3
loading translations [en]... locale_dir /home/one/github/Varie/pyTermTk/docs/source/locales/en/LC_MESSAGES does not exist
locale_dir /home/one/github/Varie/pyTermTk/docs/source/locales/en/LC_MESSAGES does not exist
done
<AutoDocGen> Visiting module: TermTk 
<AutoDocGen> Visiting module: TermTk.TTkAbstract 
<AutoDocGen> Visiting module: TermTk.TTkAbstract.abstractitemmodel 

Traceback (most recent call last):
  File "/home/one/github/Varie/pyTermTk/.venv/lib/python3.11/site-packages/sphinx/events.py", line 404, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/one/github/Varie/pyTermTk/.venv/lib/python3.11/site-packages/sphinxcontrib_autodocgen/__init__.py", line 138, in <lambda>
    self.app.connect('config-inited', lambda app, config: self.generateAll())
                                                          ^^^^^^^^^^^^^^^^^^
  File "/home/one/github/Varie/pyTermTk/.venv/lib/python3.11/site-packages/sphinxcontrib_autodocgen/__init__.py", line 147, in generateAll
    self.generate()
  File "/home/one/github/Varie/pyTermTk/.venv/lib/python3.11/site-packages/sphinxcontrib_autodocgen/__init__.py", line 178, in generate
    self.visit_module(mod)
  File "/home/one/github/Varie/pyTermTk/.venv/lib/python3.11/site-packages/sphinxcontrib_autodocgen/__init__.py", line 300, in visit_module
    if not self.visit_module(submodule): continue
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/one/github/Varie/pyTermTk/.venv/lib/python3.11/site-packages/sphinxcontrib_autodocgen/__init__.py", line 300, in visit_module
    if not self.visit_module(submodule): continue
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/one/github/Varie/pyTermTk/.venv/lib/python3.11/site-packages/sphinxcontrib_autodocgen/__init__.py", line 329, in visit_module
    permittedmembers = set(memberinfo[0] for memberinfo in documenter.get_object_members(want_all=True)[1])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/one/github/Varie/pyTermTk/.venv/lib/python3.11/site-packages/sphinxcontrib_autodocgen/__init__.py", line 329, in <genexpr>
    permittedmembers = set(memberinfo[0] for memberinfo in documenter.get_object_members(want_all=True)[1])
                           ~~~~~~~~~~^^^
TypeError: 'ObjectMember' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/one/github/Varie/pyTermTk/.venv/lib/python3.11/site-packages/sphinx/cmd/build.py", line 496, in build_main
    app = Sphinx(
          ^^^^^^^
  File "/home/one/github/Varie/pyTermTk/.venv/lib/python3.11/site-packages/sphinx/application.py", line 280, in __init__
    self.events.emit('config-inited', self.config)
  File "/home/one/github/Varie/pyTermTk/.venv/lib/python3.11/site-packages/sphinx/events.py", line 415, in emit
    raise ExtensionError(
sphinx.errors.ExtensionError: Handler <function AutoDocGen.connect.<locals>.<lambda> at 0x7f1312ffdc60> for event 'config-inited' threw an exception (exception: 'ObjectMember' object is not subscriptable)

Extension error (sphinxcontrib_autodocgen):
Handler <function AutoDocGen.connect.<locals>.<lambda> at 0x7f1312ffdc60> for event 'config-inited' threw an exception (exception: 'ObjectMember' object is not subscriptable)

```

**Comment by ben-spiller** [comment]
Thanks for the report. I finally found time to do another release with the fixes for recent sphinx versions - 1.4 fixes this
